export const endPoints = {
  users: "users",
  admins: "admins",
  classes: "classes",
  login: "users/login",
  profile: "users/profile",
  "delete-many": "delete-many",
  exams: "exams",
  courses: "courses",
  "student-courses": "student-courses",
  teachers: "teachers",
  students: "students",
  "refresh-token": "users/refresh-token",
  "exam-results": "exam-results",
  "time-table": "time-table",
  attendances: "attendances",
  count: "admins/count",
};
